---
title: "barplot1"
author: "Bineta  Faye"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Essai

## Données dans le cas de tissus normaux 01

```{r}
data_exp1<- read.csv("~/Downloads/expression_data_tsg3_3686_samples_20982_genes.csv", header=TRUE, sep=";")
```

```{r}
data_exp2=read.csv("~/Downloads/expression_data_tsg3_3686_samples_20982_genes__targets.csv", header=TRUE, sep=";")
```

```{r}
data_exp1[1:3,1:5]
data_exp2[1:3,1:5]
```

## on ecrit une fonction pour la visualisation 


```{r,echo=FALSE}
visual=function(gene="MLF1",level=1){
n=dim(data_exp1)[2]
exp_gene=c()
for(i in 3:n){
  exp_gene[i-2]=data_exp1[data_exp1$gene_symbols==gene,i]}
###################################  
if(level==1)
    tissue=paste0(data_exp2$tissue_group_level1,"-",data_exp2$tissue_stage)
if(level==2)
  tissue=paste0(data_exp2$tissue_group_level2,"-",data_exp2$tissue_stage)
if(level==3)
  tissue=paste0(data_exp2$tissue_group_level3,"-",data_exp2$tissue_stage)
  
#################################  
X=data.frame(id_sample=data_exp2$id_sample,tissue,exp_gene)
#head(X)
moyenne <- aggregate(X$exp_gene ~ X$tissue, FUN=mean)
moyenne=as.data.frame(moyenne)
#moyenne
###################################
cols=rep("grey",dim(moyenne)[1])
for(i in 1:dim(moyenne)[1]){
  if((moyenne[i,1]=="bone_marrow-adult") |( (moyenne[i,1]=="haematopoietic_div-adult") |(moyenne[i,1]=="hematopoietic-adult")))
    cols[i]="light green"
  else 
    if (moyenne[i,1]=="testis-adult"|moyenne[i,1]=="germinal-adult" |moyenne[i,1]=="male_germinal-adult")
      cols[i]="light blue"
}
par(cex.axis=0.4)
barplot(moyenne[,2],col = cols,las=3,axis.lty=1,cex.axis = 0.5)#,main=paste0("exp ",gene," level",level),names.arg = moyenne[,1]
}
```



```{r,dpi=300}
visual(gene="NUTM1")
#visual(gene="ADSS1",level=2)
#visual(gene="NUTM1",level=3)
#visual(gene="MLF1",level = 2)
```

